# Generated by Django 5.0.6 on 2024-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_element_id_alter_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
