# Generated by Django 5.0.6 on 2024-10-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_page_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='css_file',
        ),
        migrations.AddField(
            model_name='theme',
            name='accent',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='accent_hov',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='accent_text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='back',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='backimg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='css',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='text',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
