# Generated by Django 5.0.6 on 2024-10-31 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_remove_theme_css_file_theme_accent_theme_accent_hov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='builder.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='backimg',
            field=models.CharField(default='none', max_length=256, null=True),
        ),
    ]
